### PR TITLE
Add async support to the CircuitBreaker

### PR DESCRIPTION
**Pull request by simonjdt**
Hi Pete

I've added the async support for the CircuitBreaker including the ability to support cancellation of the tasks.

Please could you merge the changes if you think they look ok?

Thanks

Simon

### CODE REVIEW

**Comment by RokitSalad** [comment]
Cheers Simon. I've got a few comments:

The tests catch both AggregateException and Exception and put the result into the same _caughtException field - it would be more explicit to have 2 fields, one _caughtExceptionFromAggregate, so it's clear how the exception was caught.

Some tests don't include the catch for AggregateException - if there is a failure in the async execution then that exception could be swallowed.

Not sure about updating the version to 4.6 - I know the syntax is nicer but maintaining backwards compatility without dragging Bcl libraries around is important to me. 

Both ExecuteTheActionAsync and ExecuteTheDelegate seem to do exactly the same thing but one injects a task and one creates it - could these be refactored to reuse the same code?

Can you take a look at those? Give me a shout if you want to query :)

**Comment by simonjdt** [comment]
Hi Pete

Thanks for the comments.  I’ll take another look at it and let you know when it’s done.

Cheers

Simon

**Comment by simonjdt** [comment]
Hi Pete

With regard to the refactoring of ExecuteTheActionSync and ExecuteTheDelegate – if I make the change then the InnerException received from the calls to Execute change to AggregateExceptions which would involve refactoring quite a few of the tests for the Execute method which seems like extra effort for not much benefit.

As for the upgrade to version 4.6, I picked the latest, because I had to upgrade to 4.5 to get async support.  If we leave it on 4 then we’d need to use the async targeting pack, but this would still mean that it was no longer compatible with Visual Studio 2010.

Cheers

Simon

**Comment by RokitSalad** [comment]
There are NuGet packages that need updating for the new .NET version. Then I'll be happy to merge.

**Pull request merged**
